### ISSUE TITLE
Suggestion: Add a link to the iRacing SDK Documentation

### ISSUE THREAD

**Issue by RiddleTime** [mherbold/IRSDKSharper#2]
Hi!

First of all, I really appreciate the approach of this library, straight forward and pretty much future proof.

I do have a suggestion, which is to add a link for the https://sajax.github.io/irsdkdocs/ so you have a reference for all the names of the members in the Telemetry. (Perhaps in the Readme)

But great job, thank you!

**Comment by mherbold** [comment]
I would actually recommend trying running the [IRSDKSharperTest](https://github.com/mherbold/IRSDKSharperTest) which will show you the names and the definitions of each telemetry data straight from the iRacing simulator.  I found that irsdkdocs tend to be outdated or even wrong in some areas.

**Comment by RiddleTime** [comment]
That's a proper debug tool for the SDK!

The problem I had is that I don't have a subscription to iRacing yet, so those docs at least helped me out to figure out the strings to use, but I got your library to work in dev branch of https://github.com/RiddleTime/Race-Element by letting a friend test it 👍 

Let me know how I should credit your code.  @mherbold 
https://github.com/RiddleTime/Race-Element/blob/dev/Race%20Element.Data/Games/iRacing/IRacingDataProvider.cs
