### ISSUE TITLE
Only connecting when iRacing is already open.

### ISSUE THREAD

**Issue by joshua-adriftdev** [mherbold/IRSDKSharper#3]
Hi there!
I've recently creating a fresh project utilising this amazing project, however I'm running into an issue. Currently, my software only connects when iRacing is already open. If I start the software with iRacing closed, and then open iRacing, it never connects.
This is what is in my Debug Output:
```'SubparRacing.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Emit.Lightweight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubparRacing.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Hosting environment: Production
Microsoft.Hosting.Lifetime: Information: Content root path: E:\Subpar Racing\SubparRacing\SubparRacing\bin\Debug\net8.0-windows
The thread '[Thread Destroyed]' (68636) has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (69656) has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (62020) has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (73108) has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (26296) has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (61228) has exited with code 0 (0x0).
```

All of this occurs whether I start loading iRacing or not (Rules out something going wrong due to opening iRacing)

The `Thread Destroyed` messages concern me, but I am also new to C# Desktop Applications- so maybe they are of no concern.

# My TelementryService.cs File
```using IRSDKSharper;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SubparRacing
{
    public class TelemetryService
    {
        public event Action<string> OnRPM;
        public event Action OnStart;

        public IRacingSdk irsdk { get; }

        public TelemetryService()
        {
            irsdk = new IRacingSdk();

            irsdk.OnException += OnException;
            irsdk.OnConnected += OnConnected;
            irsdk.OnDisconnected += OnDisconnected;
            irsdk.OnStopped += OnStopped;
            irsdk.OnTelemetryData += OnTelemetryData;

            // this means fire the OnTelemetryData event every 30 data frames (2 times a second)
            irsdk.UpdateInterval = 30;
        }

        private void OnTelemetryData()
        {
            Debug.WriteLine("Telem Data");
            var rpm = irsdk.Data.GetValue("RPM");

            OnRPM?.Invoke($"RPM: {rpm}");
        }

        public void Start()
        {
            Debug.WriteLine("Starting...");
            irsdk.Start();   
        }

        public void Stop() {
            irsdk.Stop();
        }

        private void OnStopped()
        {
            Stop();
        }

        private void OnDisconnected()
        {
            Debug.WriteLine("Disconnected.");
        }

        private void OnConnected()
        {
            Debug.WriteLine("Connected.");
            OnStart?.Invoke();
        }

        private void OnException(Exception exception)
        {
            Debug.Write("Exception: " + exception);
        }

    }
}
```

The Start() function is called from inside my App.cs file, when the application starts:
```private void OnStartup(object sender, StartupEventArgs e)
{
    TelemetryService = new TelemetryService();
    _host.Start();
    
    TelemetryService.Start();
}
```

I hope this is an easy fix, if I can provide any further information I'd be more than happy to do so.
Thanks again!

**Comment by joshua-adriftdev** [comment]
I hate to say it... I turned my PC off and back on again and it worked perfectly. If this issue reoccurs I'll keep you posted.

**Comment by joshua-adriftdev** [comment]
Well, this got a whole lot weirder. I initially turned my PC off and back on, and then all of a sudden it was able to connect when the application was open before iRacing. However, after doing some more development, it all of a sudden stopped being able to. Once again, I turned my PC back off and on and again, and it worked perfectly. 

I have very little clue what the issue is, and I'd truly appreciate your help.

**Comment by mherbold** [comment]
Hmm - I have a bunch of apps using IRSDKSharper and all of them work either with the iRacing simulator already running or started up afterwards.  When you say "iRacing is already open" you mean the actual simulator that gets launched when you join a race or a start a replay, right?  Not the iRacing UI which is just the front end, and doesn't have any telemetry.

Try adding a callback to irsdk.OnDebugLog and that'll give you a lot more information as to what is going on.

`irsdk.OnDebugLog += OnDebugLog;`

`private void OnDebugLog( string message )
{
    Debug.WriteLine( message )
}`

It's weird that you are calling Stop() inside of OnStopped().

**Comment by joshua-adriftdev** [comment]
Hey There.
I did mean the Simulator when referring to 'iRacing already being open', apologies for not clarifying.
Adding the debug logs didn't actually seem to do anything- I didn't notice any debug messages being printed in my Output.

I have no idea why I called `Stop()` inside of `OnStopped()`, I deleted it but it made no different to my issue.

I have noticed something interesting however, the first time I load my software after restarting my PC, I am able to open/close the iRacing Simulator multiple times, and each time it connects. However after I close my software and open it again, then it becomes unable to connect to the iRacing Simulator. 
Additionally, when I close my software after running it for the first time, I don't see the Debug message for `OnStopped()` being called, but I do each time I restart the software after that.

Here is my repository: [https://github.com/joshua-adriftdev/SubparRacing](https://github.com/joshua-adriftdev/SubparRacing)

The TelementryService.cs class holds my IRSDKSharper instance, and I run Start/Stop in the App.cs file.
I have also tried moving all of the IRSDK-related code into the MainWindow.cs, but faces the same issue.

Thanks!

**Comment by mherbold** [comment]
Not seeing any debug output when you have irsdk.OnDebugLog hooked up and passing messages to Debug.WriteLine is very suspect.  I can take a look at your repo this weekend, but my feeling is that, from what you say (working the first time, not working after that) is that there is something funky going on when you launch it - like it is staying in the background even after you close the app.

Meanwhile, here's a few ideas -

1. How are you using IRSDKSharper?  Are you including the project directly in yours, or are you using Nuget?
2. If via Nuget - what version do you have installed?  You should be using the latest (1.1.0 at this time).
3. Can you send me the full output window you see when you run it for the first time, and the full output window each time you run it afterwards?
4. Instead of using Nuget, you can download IRSDKSharper directly from Github, and include it in your project as a project reference.  Then you can add breakpoints in Start(), Stop(), ConnectionLoop(), etc.  My feeling is that when you run your app for the 2nd time, something like MemoryMappedFile.OpenExisting(), or memoryMappedFile.CreateViewAccessor(), or one of those related Windows API calls in ConnectionLoop() is failing.
5. You can put breakpoints in your own app functions to make sure its running the way you expected it to run.

**Comment by joshua-adriftdev** [comment]
Well, I think we've got the issue now. After installing IRSDKSharper via a Project Reference instead of NuGet (The way I originally was), the debug logs started working.

This was the first time I launched it (where it worked), I also restarted the sim multiple times while the first software instance was open, and everything worked perfectly: [https://pastecode.io/s/d0hvrvmk](https://pastecode.io/s/d0hvrvmk)

The 2nd time I open it, these are the debug logs I see immediately after opening the software. iRacing Simulator is NOT running:
```Starting...
IRSDKSharper is starting.
IRSDKSharper has been started.
Connection loop has been started.
memoryMappedFile != null
Connection loop has been stopped.
```

Full log of the 2nd software instance: [https://pastecode.io/s/78ksg0zj](https://pastecode.io/s/78ksg0zj)

From what I can tell using Process Explorer, the application doesn't continue to run any processes after being closed.

I'll fiddle with what I can to see if I can get this fixed, but I highly doubt I'm going to get anywhere.
Thanks for your help so far, and for the tip on installing without NuGet.

**Comment by joshua-adriftdev** [comment]
After some debug logs & whatnot, I found that
`var errorCode = Marshal.GetLastWin32Error();` is `2`- ERROR_FILE_NOT_FOUND.

I've just added
```
if (errorCode == 2)
{
    Thread.Sleep(2000);
    continue;
}
```
(No I do not feel good about this lol) It's an incredibly temporary and rudimentary fix so I can keep going with development,

I look forwards to hearing your thoughts on how to actually fix it. I should be able to try any suggestions you have first thing tomorrow morning.

**Comment by mherbold** [comment]
Nice work narrowing down the cause.

What line did you insert your hacky code into IRacingSdk.cs?  It's really strange because it should have caught any file not found exception in the try / catch around MemoryMappedFile.OpenExisting.

**Comment by mherbold** [comment]
Another thought - are you calling irsdk.Stop() when your app is ready to exit?  I am wondering if  you're not doing that then its possible that some things are not cleaned up from the last app run, and those things are interfering with the next app run.

For an example, look at my small iRacingStages app here - https://github.com/mherbold/iRacingStages

You'll note that in MainWindow.xaml.cs  I have a Window_Closing event handler which calls irsdk.Stop().

**Comment by joshua-adriftdev** [comment]
# 'Hacky' Fix
> Nice work narrowing down the cause.
> 
> What line did you insert your hacky code into IRacingSdk.cs? It's really strange because it should have caught any file not found exception in the try / catch around MemoryMappedFile.OpenExisting.

The code I added was in `IRacingSdk#ConnectionLoop`:
```
if ( hEvent == (IntPtr) null )
{
    var errorCode = Marshal.GetLastWin32Error();
    // If the error code is FileNotFound, wait 2 seconds and try to connect again
    if (errorCode == 2)
    {
        Thread.Sleep(2000);
        continue;
    }
    
    Marshal.ThrowExceptionForHR( errorCode, IntPtr.Zero );
}
```
As I stated earlier, it's only a temporary fix that allows me to keep working on my project.

# Window_Closing
> Another thought - are you calling irsdk.Stop() when your app is ready to exit? I am wondering if you're not doing that then its possible that some things are not cleaned up from the last app run, and those things are interfering with the next app run.
> 
> For an example, look at my small iRacingStages app here - https://github.com/mherbold/iRacingStages
> 
> You'll note that in MainWindow.xaml.cs I have a Window_Closing event handler which calls irsdk.Stop().

While I was calling `irsdk.Stop()` in my `App.cs` class in my `OnExit` method, I tried adding a `Window_Closing` event handler to my `MainWindow.xaml.cs`, but the issue persisted.

**Comment by mherbold** [comment]
Ok Joshua - I updated IRSDKSharper to 1.1.2 with added code to address the possibility that getting the event handler could fail with a file not found error.  I tested the code out but since I cannot reproduce the exact error you are getting, I suggest getting package 1.1.2 and testing it out and letting me know if the fix works or not.  Thank you for your help!

**Comment by joshua-adriftdev** [comment]
Apologies for the delay, I only just had a chance to test it, and as far as I can see it seemed to work perfectly.
Thank you for all of your help!

**Comment by mherbold** [comment]
Thank you for your help as well!  :-)
